set positional-arguments := true

set shell := ["bash", "-euco", "pipefail"]

[no-cd]
_default:
    @just --list --list-submodules

fmt-just:
    @just --fmt --unstable

setup:
  printf "mini.nvim & tests"
  mkdir -p deps
  git clone --filter=blob:none https://github.com/nvim-mini/mini.nvim deps/mini.nvim

test:
	nvim --headless --noplugin -u scripts/minimal_init.vim -c "PlenaryBustedDirectory tests/ { minimal_init = './scripts/minimal_init.vim' }"
